trigger:
- master
- patch_branch

stages:

#####################################
# Linux Stages - Microsoft Hosted VMs
#####################################

  ### Linux Build Stage ###
- stage: linux_build_stage
  displayName: 'Building package on Ubuntu-16.04'
  jobs:
  - job: buildRepo
    displayName: 'Compile Package'
    timeoutInMinutes: 150
    pool:
      vmImage: 'ubuntu-16.04'
    steps:
    # Manually adding conda to the PATH is a step required by Microsoft
    - bash: echo "##vso[task.prependpath]$CONDA/bin"
      displayName: 'Add conda to PATH'
    - task: CondaEnvironment@0
      inputs:
        environmentName: 'Build'
        packageSpecs: 'python=2.7'
    - bash: |
        conda install --yes --quiet -c conda-forge/label/cf201901 -c fermi fermi-repoman scons swig
        conda install --yes --quiet --only-deps -c conda-forge/label/cf201901 -c fermi fermitools
      displayName: 'Setup Build environment'
    - bash: |
        cd ..
        repoman --remote-base https://github.com/fermi-lat checkout --force --develop ScienceTools conda
      displayName: 'Clone Repos'
    - bash: |
        mkdir -p ${CONDA_PREFIX}/include/fftw
        ln -s ${CONDA_PREFIX}/include/fftw3.* ${CONDA_PREFIX}/include/fftw
      displayName: 'FFTW relinking'
    - bash: scons -C ScienceTools --site-dir=../SConsShared/site_scons --with-cc=/usr/bin/gcc --with-cxx=/usr/bin/g++ --ccflags="-O2" --cxxflags="-O2 -std=c++11" --conda=$CONDA_PREFIX tip
      displayName: 'Compile Package'

- stage: pipeline_launch_stage
  displayName: 'Launch Fermitools CI Pipeline'
  condition: succeeded('linux_build_stage')
  jobs:
  - job: 
    steps:
    - bash: |
        cd ../
        git clone https://github.com/fermi-lat/fermitools-Conda
        cd fermitools-Conda
        echo "##vso[task.setvariable variable=version]$(grep -i 'set version' meta.yaml | awk '{ print $5}' | sed 's/"//g' | cut -d "." -f 1)"
        echo "##vso[task.setvariable variable=revision]$(grep -i 'set version' meta.yaml | awk '{ print $5}' | sed 's/"//g' | cut -d "." -f 2)"
        echo "##vso[task.setvariable variable=patch]$(grep -i 'set version' meta.yaml | awk '{ print $5}' | sed 's/"//g' | cut -d "." -f 3)"
        echo Version is $(version).$(revision).$(patch)